name: Scala CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.17
      uses: actions/setup-java@v3
      with:
        distribution: oracle
        java-version: 17
    - name: Run tests
      run: sbt -Dsbt.log.noformat=true test
